"""preserve incident history on delete

Revision ID: 0174b14e5eb8
Revises: 71fe9ffb7d60
Create Date: 2026-08-11 18:52:55.362076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0174b14e5eb8'
down_revision: Union[str, Sequence[str], None] = '71fe9ffb7d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident_history', 'incident_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('incident_history_incident_id_fkey'), 'incident_history', type_='foreignkey')
    op.create_foreign_key(None, 'incident_history', 'incidents', ['incident_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident_history', type_='foreignkey')
    op.create_foreign_key(op.f('incident_history_incident_id_fkey'), 'incident_history', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    op.alter_column('incident_history', 'incident_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
