"""add_ai_analysis_fields_to_incidents

Revision ID: 072c276c6ffa
Revises: 46c20be4c301
Create Date: 2026-07-23 19:24:56.310714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072c276c6ffa'
down_revision: Union[str, Sequence[str], None] = '46c20be4c301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('predicted_severity', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('predicted_category', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('recommended_response', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'recommended_response')
    op.drop_column('incidents', 'ai_summary')
    op.drop_column('incidents', 'predicted_category')
    op.drop_column('incidents', 'predicted_severity')
    # ### end Alembic commands ###
