"""add AI confidence fields

Revision ID: 3b3ff5f65cd9
Revises: 0174b14e5eb8
Create Date: 2026-08-11 19:49:28.888892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3ff5f65cd9'
down_revision: Union[str, Sequence[str], None] = '0174b14e5eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('severity_confidence', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('category_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'category_confidence')
    op.drop_column('incidents', 'severity_confidence')
    # ### end Alembic commands ###
