"""add incident priority

Revision ID: c87596f9a41d
Revises: 3b3ff5f65cd9
Create Date: 2026-08-12 18:03:06.707388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87596f9a41d'
down_revision: Union[str, Sequence[str], None] = '3b3ff5f65cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'incidents',
        sa.Column(
            'priority',
            sa.String(length=20),
            nullable=False,
            server_default='medium',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'priority')
    # ### end Alembic commands ###